name: team-service
replicaCount: 2
rollingUpdate:
  type: RollingUpdate
  maxUnavailable: 1
  maxSurge: 1
image:
  name: maheshnandi/gamesbond-team-service
  tag: dev
  pullPolicy: Always
resources:
  requests:
    cpu: "100m"
    memory: "128Mi"
  limits:
    cpu: "300m"
    memory: "256Mi"
service:
  port: 4003
  targetPort: 4003
config:
  mongourl: "mongodb://mongo:27017"
  redisurl: "redis://redis:6379"
